# Generated by Django 3.0.6 on 2021-05-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
